baseURL = "http://www.bobwhitemedia.com/hugo_quickstart/"
languageCode = "en-us"
title = "Bob's Hugo Quickstart"
theme = "ananke"


[params]
	description = "The last theme you'll ever need. Maybe."
	twitter = "https://twitter.com/lg3bass"
	instagram = "https://www.instagram.com/lg3bass/"
  	youtube = "https://www.youtube.com/user/lg3bass"
  	github = "https://github.com/lg3bass"
	background_color_class = "bg-navy"
	featured_image = "/images/BG_TEST.jpg"